WEBHOOK_PASSPHRASE = "PASSPHRASE"

#Binance Sandbox
BINANCE_API_KEY = 'YOUR API KEY'
BINANCE_API_SECRET = 'YOUR API SECRET'
BINANCE_API_URL = 'https://testnet.binance.vision/api'

#CB PRO Account
CB_PRO_PASSPHRASE = 'YOUR PASSWORD'
CB_PRO_API_KEY = 'YOUR API KEY'
CB_PRO_API_SECRET = 'YOUR API SECRET'

#CB Account
CB_API_KEY = 'YOUR API KEY'
CB_API_SECRET = 'YOUR API SECRET'
